version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:latest
    restart: always
    volumes:
      - ./data/redis:/data  
